apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: onboard
        version: blue
    spec:
      containers:
      - image: viejo/app:blue
        name: blue
        ports:
        - containerPort: 8000
          name: http
